# name: brew test-bot
# on:
#   pull_request:
#     paths:
#       - "Formula/cod-cli.rb"
#   push:
#     paths:
#       - "Formula/cod-cli.rb"
#   workflow_dispatch:

# permissions:
#   contents: read
#   pull-requests: write

# jobs:
#   test-bot:
#     runs-on: macos-latest
#     steps:
#       - name: Set up Git repository
#         uses: actions/checkout@v4
#         with:
#           show-progress: false
#       - name: Run brew test-bot
#         run: |
#           set -e
#           brew update
#           HOMEBREW_TAP_DIR="/usr/local/Homebrew/Library/Taps/govwifi/homebrew-cod"
#           sudo mkdir -p "$HOMEBREW_TAP_DIR"
#           sudo rm -rf "$HOMEBREW_TAP_DIR"
#           sudo ln -s "$PWD" "$HOMEBREW_TAP_DIR"
#           brew test-bot --tap=govwifi/cod cod-cli
#         env:
#           HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.COD_TOKEN }}

